application: forthsalon-hrd
version: 3
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1m"

builtins:
- deferred: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: text/html

- url: /favicon.png
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /admin/.*
  script: forthsalon.app
  login: admin

- url: /.*
  script: forthsalon.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

