application: forthsalon-hrd
version: 3
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "10m"


handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: text/html

- url: /haiku-view/ahBzfmZvsb24taHJkcg0LEgVIYWlrdRj46RYM
  static_files: canned/ahBzfmZvsb24taHJkcg0LEgVIYWlrdRj46RYM
  upload: canned/ahBzfmZvsb24taHJkcg0LEgVIYWlrdRj46RYM
  mime_type: text/html

- url: /haiku-view/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRj16RYM
  static_files: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRj16RYM
  upload: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRj16RYM
  mime_type: text/html

- url: /haiku-view/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiCqRwM
  static_files: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiCqRwM
  upload: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiCqRwM
  mime_type: text/html

- url: /haiku-view/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiCuBcM
  static_files: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiCuBcM
  upload: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiCuBcM
  mime_type: text/html

- url: /haiku-view/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiHuBcM
  static_files: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiHuBcM
  upload: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiHuBcM
  mime_type: text/html

- url: /haiku-view/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiYlRMM
  static_files: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiYlRMM
  upload: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRiYlRMM
  mime_type: text/html

- url: /haiku-view/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRjG_xQM
  static_files: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRjG_xQM
  upload: canned/ahBzfmZvcnRoc2Fsb24taHJkcg0LEgVIYWlrdRjG_xQM
  mime_type: text/html

- url: /haiku-view/ahBzfmZvsb24taHJkcg0LEgVIYWlrdRj46RYM
  static_files: canned/ahBzfmZvsb24taHJkcg0LEgVIYWlrdRj46RYM
  upload: canned/ahBzfmZvsb24taHJkcg0LEgVIYWlrdRj46RYM
  mime_type: text/html

- url: /favicon.png
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /admin/.*
  script: forthsalon.app
  login: admin

- url: /.*
  script: forthsalon.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

