runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1m"

builtins:
- deferred: on

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /favicon(.*)
  static_files: static/favicon\1
  upload: static/favicon.*
  secure: always

- url: /admin/.*
  script: forthsalon.app
  login: admin
  secure: always

- url: /.*
  script: forthsalon.app
  secure: always


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
