application: iconforth-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1h"

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /
  static_files: html/main.html
  upload: html/main.html
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /html
  static_dir: html
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*
  script: iconforth.app
