application: forthsalon-hrd
version: 1
runtime: python
api_version: 1

default_expiration: "10m"

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /favicon.png
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /admin/.*
  script: forthsalon.py
  login: admin

- url: /.*
  script: forthsalon.py
